### ISSUE TITLE
Why GPL license?

### ISSUE THREAD

**Issue by derwaldgeist** [pzmudzinski/UnitySpeechRecognizer#6]
This makes it impossible to use in commercial contexts. Also, the Asset Store Version mentions the Unity EULA. So, does this mean that this code is double-licensed?!

**Comment by pzmudzinski** [comment]
Why would it make it impossible to use in commercial software?

**Comment by derwaldgeist** [comment]
Because GPL prevents this. In this case, the whole software would have to be GPL. You could use LGPL, however, which is compatible with commercial use.

**Comment by pzmudzinski** [comment]
"Software under the GPL may be run for all purposes, including commercial purposes and even as a tool for creating proprietary software, such as when using GPL-licensed compilers. Users or companies who distribute GPL-licensed works (e.g. software), may charge a fee for copies or give them free of charge."

**Comment by derwaldgeist** [comment]
Yes. But don't you have to open up your own code to the public then?

**Comment by pzmudzinski** [comment]
Isn't it open to the public? Anyone can copy and modify and use however they want.
